[[main]]
  identifier = "Question Bank"
  name = "Question Bank"
  url = "qb"
  weight = 1
  
[[main]]
  parent = "Question Bank"
  name = "Botany"
  url = "gallery/bot" 
  
[[main]]
  parent = "Question Bank"
  name = "Zoology"
  url = "gallery/zoo" 
  
[[main]]
  parent = "Question Bank"
  name = "Chemistry"
  url = "gallery/chem" 
 
[[main]]
  parent = "Question Bank"
  name = "Physics"
  url = "gallery/phy" 
  
[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 4

#[[main]]
#  identifier = "archive"
#  name = "Archive"
#  url = "archive"
#  weight = 2

#[[main]]
#  identifier = "presentation"
#  name = "Pt"
#  url = "presentation"
#  weight = 3

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2

#[[main]]
#  identifier = "showcase"
#  name = "Showcase"
#  url = "showcase"
#  weight = 6

#[[main]]
#  identifier = "publication"
#  name = "Pub"
#  url = "publication"
#  weight = 7
